# Use the official Go image for building the app
FROM golang:1.23 as builder

# Set working directory
WORKDIR /app

# Copy project files
COPY . .

# Build the application
RUN go build -o server ./cmd/app

# Use a minimal image for deployment
FROM alpine:latest

WORKDIR /root/

# Copy the compiled binary and static files
COPY --from=builder /app/server .
COPY --from=builder /app/internal/static ./static/
COPY --from=builder /app/internal/templates ./templates/

# Expose the application port
EXPOSE 8080

# Run the server
CMD ["./server"]